Default: &defaults
  user: matemat
  password: "1234"
  host: astrom.hq.c3d2.de
  port: 5432
  database: matemat
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: PROJECTNAME_test
  <<: *defaults

Staging:
  database: PROJECTNAME_staging
  poolsize: 100
  <<: *defaults

Production:
  database: PROJECTNAME_production
  poolsize: 100
  <<: *defaults
