Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://localhost:3000"
  copyright: Insert copyright statement here
  mailpath: "/usr/sbin/exim4"
  mailoptions: ["-t", "-f no-reply@c3d2.de"]
  mailfrom: "no-reply@c3d2.de"
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  #approot: "http://www.example.com"
  <<: *defaults
